import React, { useEffect, useState } from 'react'
import {
  Truck,
  Plus,
  Search,
  CheckCircle2,
  AlertTriangle,
  X,
  ShieldAlert,
  ArrowRight,
  Send,
  Barcode,
  Scan,
  RefreshCw,
  Clock,
  Sparkles,
  MessageSquare,
  AlertCircle,
  Warehouse,
} from 'lucide-react'
import apiClient from '@/api/client'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table'

interface DeliveryChallan {
  id: string
  dc_number: string
  from_location: string
  to_location: string
  items_count: number
  total_units: number
  status: 'in_transit' | 'delivered' | 'mismatch' | 'draft'
  dispatched_at: string
  expected_arrival: string
  sync_check_status: 'synced' | 'mismatch_detected'
  lost_in_transit_qty: number
}

const DEFAULT_DCS: DeliveryChallan[] = [
  {
    id: '1',
    dc_number: 'DC-202608-TR01',
    from_location: 'Main Dark Store Bengaluru',
    to_location: 'Sub-WH Indiranagar (VM-04)',
    items_count: 3,
    total_units: 120,
    status: 'in_transit',
    dispatched_at: '2026-08-19 10:30 AM',
    expected_arrival: '2026-08-19 04:00 PM',
    sync_check_status: 'synced',
    lost_in_transit_qty: 0,
  },
  {
    id: '2',
    dc_number: 'DC-202608-TR02',
    from_location: 'Sub-WH Koramangala',
    to_location: 'Sub-WH Whitefield (Out of Stock Refill)',
    items_count: 2,
    total_units: 60,
    status: 'in_transit',
    dispatched_at: '2026-08-19 08:00 AM',
    expected_arrival: '2026-08-19 02:00 PM',
    sync_check_status: 'mismatch_detected',
    lost_in_transit_qty: 0,
  },
  {
    id: '3',
    dc_number: 'DC-202608-TR03',
    from_location: 'Main Dark Store Bengaluru',
    to_location: 'Vending Fleet #07',
    items_count: 5,
    total_units: 150,
    status: 'delivered',
    dispatched_at: '2026-08-18 02:00 PM',
    expected_arrival: '2026-08-18 06:00 PM',
    sync_check_status: 'synced',
    lost_in_transit_qty: 0,
  },
]

// Sample sub-warehouse out-of-stock items requiring auto DC
const OUT_OF_STOCK_SUB_WH_ITEMS = [
  {
    product: 'Lays Classic Salted 50g',
    sku: 'SNK-LAY-50',
    sub_wh: 'Sub-WH Whitefield',
    current_stock: 0,
    required_stock: 40,
    source_recommendation: 'Sub-WH Koramangala (Surplus: 45 units available)',
    status: 'pending_dc_generation',
  },
  {
    product: 'Snickers Chocolate Bar 50g',
    sku: 'CHO-SNK-50',
    sub_wh: 'Sub-WH Indiranagar',
    current_stock: 0,
    required_stock: 30,
    source_recommendation: 'Main Dark Store Bengaluru (Surplus: 120 units available)',
    status: 'pending_dc_generation',
  },
]

export default function DeliveryChallansPage() {
  const [dcs, setDcs] = useState<DeliveryChallan[]>(DEFAULT_DCS)
  const [search, setSearch] = useState('')
  const [isCreateModalOpen, setIsCreateModalOpen] = useState(false)
  const [isScannerOpen, setIsScannerOpen] = useState(false)

  // Scanner Simulator State (Photo 7 VIP Automation)
  const [scanInput, setScanInput] = useState('')
  const [scanResult, setScanResult] = useState<{
    status: 'success' | 'blocked_expired' | 'not_found' | null
    message: string
    product?: string
    expiry?: string
    batch?: string
  }>({ status: null, message: '' })

  // WhatsApp Alert State (Photo 6)
  const [whatsappSent, setWhatsappSent] = useState(false)

  // Auto DC Generation state
  const [autoDCPending, setAutoDCPending] = useState(OUT_OF_STOCK_SUB_WH_ITEMS)

  // Total in-transit metrics
  const totalInTransit = dcs.filter((d) => d.status === 'in_transit').length
  const mismatches = dcs.filter((d) => d.sync_check_status === 'mismatch_detected')
  const totalLostInTransit = dcs.reduce((acc, curr) => acc + curr.lost_in_transit_qty, 0)

  // Auto Generate DC for out-of-stock subwarehouse
  const handleAutoGenerateDC = (index: number) => {
    const item = autoDCPending[index]
    const newDC: DeliveryChallan = {
      id: String(Date.now()),
      dc_number: `DC-AUTO-${Math.random().toString(36).substring(2, 6).toUpperCase()}`,
      from_location: item.source_recommendation.split(' (')[0],
      to_location: item.sub_wh,
      items_count: 1,
      total_units: item.required_stock,
      status: 'in_transit',
      dispatched_at: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
      expected_arrival: 'Today +4 hours',
      sync_check_status: 'synced',
      lost_in_transit_qty: 0,
    }

    setDcs([newDC, ...dcs])
    setAutoDCPending(autoDCPending.filter((_, i) => i !== index))
  }

  // Barcode / Expiry Scanner Automation (Photo 7)
  const handleScanBarcode = (e: React.FormEvent) => {
    e.preventDefault()
    const term = scanInput.trim().toUpperCase()

    // Test cases for scanning automation
    if (term.includes('EXP') || term === 'BEV-PB-250-EXPIRED' || term === 'BATCH-PB-0426') {
      // EXPIRED ITEM DETECTED -> STRICT AUTOMATION BLOCK
      setScanResult({
        status: 'blocked_expired',
        message: 'BLOCKED BY EXPIRY GUARD: This product is EXPIRED (Expiry: 2026-08-10). Automated block prevented dispatch/scan!',
        product: 'Paper Boat Mango 250ml',
        expiry: '2026-08-10 (Expired 9 days ago)',
        batch: 'BATCH-PB-0426',
      })
    } else if (term === 'BEV-RB-250' || term.includes('RED') || term === 'BATCH-RB-0826') {
      setScanResult({
        status: 'success',
        message: 'SCAN VERIFIED: Product is fresh and eligible for dispatch.',
        product: 'Red Bull Energy Drink 250ml',
        expiry: '2027-02-28 (Fresh)',
        batch: 'BATCH-RB-0826',
      })
    } else {
      setScanResult({
        status: 'success',
        message: `SCAN VERIFIED: Barcode ${term} validated against stock ledger. Expiry check passed.`,
        product: 'Verified Inventory SKU',
        expiry: '2027-06-30 (Valid)',
        batch: `BATCH-${term.slice(0, 4)}`,
      })
    }
  }

  const triggerWhatsAppMismatchNotification = () => {
    setWhatsappSent(true)
    setTimeout(() => setWhatsappSent(false), 4000)
  }

  const filtered = dcs.filter((d) =>
    d.dc_number.toLowerCase().includes(search.toLowerCase()) ||
    d.from_location.toLowerCase().includes(search.toLowerCase()) ||
    d.to_location.toLowerCase().includes(search.toLowerCase())
  )

  return (
    <div className="space-y-6">
      {/* ── Header ── */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold tracking-tight text-foreground flex items-center gap-2">
            <Truck className="h-6 w-6 text-indigo-500" />
            Delivery Challans (DC) & Transfers
          </h1>
          <p className="text-xs text-muted-foreground mt-0.5">
            Automated inter-warehouse DC creation, in-transit sync (4x daily) & expiry scan blocker
          </p>
        </div>

        <div className="flex items-center gap-2">
          <Button
            variant="outline"
            size="sm"
            onClick={() => setIsScannerOpen(true)}
            className="gap-1.5 text-xs border-indigo-500/30 text-indigo-600 dark:text-indigo-400 hover:bg-indigo-500/10"
          >
            <Scan className="h-4 w-4" />
            Scan Barcode (Expiry Guard)
          </Button>
          <Button
            size="sm"
            onClick={() => setIsCreateModalOpen(true)}
            className="gap-1.5 shadow-sm"
          >
            <Plus className="h-4 w-4" />
            New Manual DC
          </Button>
        </div>
      </div>

      {/* ── Metric Cards ── */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
        {/* 1. In Transit */}
        <Card className="shadow-sm">
          <CardContent className="p-5">
            <div className="flex items-center justify-between">
              <span className="text-xs font-semibold text-muted-foreground uppercase tracking-wider">
                In Transit DC
              </span>
              <div className="h-8 w-8 rounded-lg bg-indigo-500/10 text-indigo-600 dark:text-indigo-400 flex items-center justify-center">
                <Truck className="h-4 w-4" />
              </div>
            </div>
            <div className="mt-3">
              <div className="text-2xl font-bold tracking-tight text-indigo-600 dark:text-indigo-400">
                {totalInTransit} Dispatches
              </div>
              <p className="text-xs text-muted-foreground mt-1">Live active shipments on route</p>
            </div>
          </CardContent>
        </Card>

        {/* 2. Lost In Transit (Must be 0%) */}
        <Card className="shadow-sm border-emerald-500/30 bg-emerald-500/5">
          <CardContent className="p-5">
            <div className="flex items-center justify-between">
              <span className="text-xs font-semibold text-emerald-600 dark:text-emerald-400 uppercase tracking-wider">
                Lost In Transit
              </span>
              <div className="h-8 w-8 rounded-lg bg-emerald-500/20 text-emerald-600 dark:text-emerald-400 flex items-center justify-center">
                <CheckCircle2 className="h-4 w-4" />
              </div>
            </div>
            <div className="mt-3">
              <div className="text-2xl font-bold tracking-tight text-emerald-600 dark:text-emerald-400">
                0% ({totalLostInTransit} units)
              </div>
              <p className="text-xs text-emerald-600/80 dark:text-emerald-400/80 mt-1 font-medium">
                Target: 0% strictly maintained ✓
              </p>
            </div>
          </CardContent>
        </Card>

        {/* 3. In-Transit Sync Check (4x/Day Mismatch Alert) */}
        <Card className={`shadow-sm ${mismatches.length > 0 ? 'border-rose-500/30 bg-rose-500/5' : ''}`}>
          <CardContent className="p-5">
            <div className="flex items-center justify-between">
              <span className="text-xs font-semibold text-muted-foreground uppercase tracking-wider">
                4x/Day Sync Mismatch
              </span>
              <div className={`h-8 w-8 rounded-lg flex items-center justify-center ${
                mismatches.length > 0 ? 'bg-rose-500/20 text-rose-600 dark:text-rose-400' : 'bg-muted text-muted-foreground'
              }`}>
                <AlertTriangle className="h-4 w-4" />
              </div>
            </div>
            <div className="mt-3">
              <div className={`text-2xl font-bold tracking-tight ${
                mismatches.length > 0 ? 'text-rose-600 dark:text-rose-400' : ''
              }`}>
                {mismatches.length} Mismatch
              </div>
              {mismatches.length > 0 ? (
                <button
                  onClick={triggerWhatsAppMismatchNotification}
                  className="flex items-center gap-1.5 mt-1.5 text-xs text-emerald-600 dark:text-emerald-400 font-bold hover:underline"
                >
                  <MessageSquare className="h-3.5 w-3.5" />
                  {whatsappSent ? 'Sent to WhatsApp!' : 'Notify on WhatsApp →'}
                </button>
              ) : (
                <p className="text-xs text-muted-foreground mt-1">All 4 daily sync cycles verified</p>
              )}
            </div>
          </CardContent>
        </Card>

        {/* 4. Sub-WH Stock Out Auto Trigger */}
        <Card className="shadow-sm border-amber-500/30 bg-amber-500/5">
          <CardContent className="p-5">
            <div className="flex items-center justify-between">
              <span className="text-xs font-semibold text-amber-600 dark:text-amber-400 uppercase tracking-wider">
                Auto-DC Queue
              </span>
              <div className="h-8 w-8 rounded-lg bg-amber-500/20 text-amber-600 dark:text-amber-400 flex items-center justify-center">
                <Sparkles className="h-4 w-4" />
              </div>
            </div>
            <div className="mt-3">
              <div className="text-2xl font-bold tracking-tight text-amber-600 dark:text-amber-400">
                {autoDCPending.length} Sub-WH Out
              </div>
              <p className="text-xs text-muted-foreground mt-1">Ready for automated surplus transfer</p>
            </div>
          </CardContent>
        </Card>
      </div>

      {/* ── Photo 7: Automated Inter-Subwarehouse DC Generator ── */}
      {autoDCPending.length > 0 && (
        <Card className="border-indigo-500/30 bg-indigo-500/5 shadow-sm">
          <CardHeader className="pb-3">
            <div className="flex items-center justify-between">
              <div>
                <CardTitle className="text-sm font-bold text-indigo-600 dark:text-indigo-400 flex items-center gap-2">
                  <Sparkles className="h-4 w-4" />
                  Automated Inter-Warehouse DC Replenishment
                </CardTitle>
                <CardDescription className="text-xs">
                  Triggered when a Sub-warehouse runs out of stock — automatically routes stock from nearest WH with surplus
                </CardDescription>
              </div>
              <Badge variant="info">Smart Routing Active</Badge>
            </div>
          </CardHeader>
          <CardContent className="space-y-3">
            {autoDCPending.map((item, idx) => (
              <div
                key={idx}
                className="p-3 rounded-lg bg-card border border-border flex flex-col md:flex-row md:items-center justify-between gap-3 text-xs"
              >
                <div className="space-y-1">
                  <div className="flex items-center gap-2">
                    <span className="font-bold text-foreground">{item.product}</span>
                    <span className="font-mono text-muted-foreground">({item.sku})</span>
                    <Badge variant="destructive" className="text-[10px]">Out of Stock at {item.sub_wh}</Badge>
                  </div>
                  <div className="text-muted-foreground flex items-center gap-1.5">
                    <ArrowRight className="h-3 w-3 text-indigo-500" />
                    <span>Auto-Source: <strong>{item.source_recommendation}</strong></span>
                  </div>
                </div>

                <div className="flex items-center gap-2 shrink-0">
                  <span className="font-semibold text-foreground">Qty: {item.required_stock} units</span>
                  <Button
                    size="sm"
                    className="h-8 text-xs gap-1.5 bg-indigo-600 hover:bg-indigo-700 text-white"
                    onClick={() => handleAutoGenerateDC(idx)}
                  >
                    <Send className="h-3.5 w-3.5" />
                    Auto-Generate DC
                  </Button>
                </div>
              </div>
            ))}
          </CardContent>
        </Card>
      )}

      {/* ── Search & Filter ── */}
      <Card className="shadow-sm">
        <CardContent className="p-4 flex flex-col sm:flex-row gap-3 items-center justify-between">
          <div className="relative w-full sm:w-80">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
            <Input
              type="text"
              placeholder="Search by DC number, destination..."
              value={search}
              onChange={(e) => setSearch(e.target.value)}
              className="pl-9 text-xs"
            />
          </div>
          <div className="flex items-center gap-2 text-xs text-muted-foreground">
            <span className="h-2 w-2 rounded-full bg-emerald-500 animate-pulse" />
            <span>4x Daily In-Transit Sync Active</span>
          </div>
        </CardContent>
      </Card>

      {/* ── DC Table ── */}
      <Card className="shadow-sm overflow-hidden">
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead>DC Number</TableHead>
              <TableHead>Origin (From)</TableHead>
              <TableHead>Destination (To)</TableHead>
              <TableHead className="text-center">Total Units</TableHead>
              <TableHead>Dispatched At</TableHead>
              <TableHead>Expected Delivery</TableHead>
              <TableHead>Transit Status</TableHead>
              <TableHead>Sync Status (4x)</TableHead>
              <TableHead className="text-right">Actions</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {filtered.map((dc) => (
              <TableRow key={dc.id} className="hover:bg-muted/40">
                <TableCell className="font-mono font-bold text-xs text-indigo-600 dark:text-indigo-400">
                  {dc.dc_number}
                </TableCell>
                <TableCell className="text-xs text-foreground font-medium">{dc.from_location}</TableCell>
                <TableCell className="text-xs text-foreground">{dc.to_location}</TableCell>
                <TableCell className="text-center font-bold">{dc.total_units} units</TableCell>
                <TableCell className="text-xs text-muted-foreground">{dc.dispatched_at}</TableCell>
                <TableCell className="text-xs text-muted-foreground">{dc.expected_arrival}</TableCell>
                <TableCell>
                  {dc.status === 'in_transit' ? (
                    <Badge variant="warning">In Transit</Badge>
                  ) : dc.status === 'delivered' ? (
                    <Badge variant="success">Delivered</Badge>
                  ) : (
                    <Badge variant="destructive">Mismatch</Badge>
                  )}
                </TableCell>
                <TableCell>
                  {dc.sync_check_status === 'synced' ? (
                    <span className="flex items-center gap-1 text-xs text-emerald-600 dark:text-emerald-400 font-medium">
                      <CheckCircle2 className="h-3.5 w-3.5" /> Synced
                    </span>
                  ) : (
                    <span className="flex items-center gap-1 text-xs text-rose-600 dark:text-rose-400 font-bold">
                      <AlertCircle className="h-3.5 w-3.5" /> Mismatch
                    </span>
                  )}
                </TableCell>
                <TableCell className="text-right">
                  <Button variant="ghost" size="sm" className="h-7 text-xs text-primary">
                    View Slip →
                  </Button>
                </TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
      </Card>

      {/* ── Photo 7 VIP: Barcode Scanner with Automatic Expiry Guard Modal ── */}
      {isScannerOpen && (
        <div className="fixed inset-0 z-50 bg-black/60 backdrop-blur-sm flex items-center justify-center p-4">
          <Card className="w-full max-w-lg bg-card border-border shadow-2xl animate-in fade-in zoom-in-95">
            <CardHeader className="flex flex-row items-center justify-between border-b border-border pb-4">
              <div>
                <CardTitle className="text-base font-bold flex items-center gap-2">
                  <Barcode className="h-5 w-5 text-indigo-500" />
                  Dispatch Barcode Scanner (Expiry Guard)
                </CardTitle>
                <CardDescription className="text-xs">
                  Automated validation prevents scanning & dispatching expired stock
                </CardDescription>
              </div>
              <Button variant="ghost" size="icon" className="h-8 w-8" onClick={() => setIsScannerOpen(false)}>
                <X className="h-4 w-4" />
              </Button>
            </CardHeader>
            <CardContent className="space-y-4 pt-5">
              <form onSubmit={handleScanBarcode} className="space-y-3">
                <div className="space-y-1">
                  <label className="text-xs font-semibold">Scan Barcode / SKU / Batch #</label>
                  <div className="flex gap-2">
                    <Input
                      autoFocus
                      placeholder="e.g. BEV-RB-250 or BATCH-PB-0426..."
                      value={scanInput}
                      onChange={(e) => setScanInput(e.target.value)}
                      className="text-xs font-mono"
                    />
                    <Button type="submit" size="sm" className="shrink-0">
                      Scan
                    </Button>
                  </div>
                </div>

                <div className="flex gap-2 text-[10px] text-muted-foreground">
                  <span>Quick Test:</span>
                  <button
                    type="button"
                    onClick={() => setScanInput('BATCH-PB-0426')}
                    className="underline text-rose-500 hover:text-rose-600"
                  >
                    Test Expired Batch
                  </button>
                  <span>•</span>
                  <button
                    type="button"
                    onClick={() => setScanInput('BEV-RB-250')}
                    className="underline text-emerald-500 hover:text-emerald-600"
                  >
                    Test Valid SKU
                  </button>
                </div>
              </form>

              {/* Scan Result Feedback */}
              {scanResult.status === 'blocked_expired' && (
                <div className="p-4 rounded-lg bg-rose-500/10 border-2 border-rose-500/50 space-y-2 animate-in shake">
                  <div className="flex items-center gap-2 text-rose-600 dark:text-rose-400 font-bold text-sm">
                    <ShieldAlert className="h-5 w-5" />
                    <span>SCAN BLOCKED — EXPIRED STOCK</span>
                  </div>
                  <p className="text-xs text-rose-600/90 dark:text-rose-400/90 font-medium">
                    {scanResult.message}
                  </p>
                  <div className="p-2.5 rounded bg-background border border-rose-500/30 text-xs space-y-1">
                    <div>Product: <strong>{scanResult.product}</strong></div>
                    <div>Expiry: <strong className="text-rose-500">{scanResult.expiry}</strong></div>
                    <div>Batch: <span className="font-mono">{scanResult.batch}</span></div>
                  </div>
                </div>
              )}

              {scanResult.status === 'success' && (
                <div className="p-4 rounded-lg bg-emerald-500/10 border-2 border-emerald-500/50 space-y-2">
                  <div className="flex items-center gap-2 text-emerald-600 dark:text-emerald-400 font-bold text-sm">
                    <CheckCircle2 className="h-5 w-5" />
                    <span>SCAN APPROVED</span>
                  </div>
                  <p className="text-xs text-muted-foreground">{scanResult.message}</p>
                  <div className="p-2.5 rounded bg-background border border-border text-xs space-y-1">
                    <div>Product: <strong>{scanResult.product}</strong></div>
                    <div>Expiry: <strong className="text-emerald-600">{scanResult.expiry}</strong></div>
                    <div>Batch: <span className="font-mono">{scanResult.batch}</span></div>
                  </div>
                </div>
              )}
            </CardContent>
          </Card>
        </div>
      )}

      {/* ── New Manual DC Modal ── */}
      {isCreateModalOpen && (
        <div className="fixed inset-0 z-50 bg-black/60 backdrop-blur-sm flex items-center justify-center p-4">
          <Card className="w-full max-w-lg bg-card border-border shadow-2xl animate-in fade-in zoom-in-95">
            <CardHeader className="flex flex-row items-center justify-between border-b border-border pb-4">
              <div>
                <CardTitle className="text-base font-bold">Create Delivery Challan (DC)</CardTitle>
                <CardDescription className="text-xs">Dispatch inventory to sub-warehouse or machine</CardDescription>
              </div>
              <Button variant="ghost" size="icon" className="h-8 w-8" onClick={() => setIsCreateModalOpen(false)}>
                <X className="h-4 w-4" />
              </Button>
            </CardHeader>
            <form onSubmit={(e) => {
              e.preventDefault()
              setIsCreateModalOpen(false)
            }}>
              <CardContent className="space-y-4 pt-5">
                <div className="space-y-1">
                  <label className="text-xs font-semibold">Dispatch From (Origin)</label>
                  <select className="w-full h-9 rounded-md border border-input bg-background px-3 py-1 text-xs">
                    <option>Main Dark Store Bengaluru</option>
                    <option>Sub-WH Koramangala</option>
                    <option>Sub-WH Whitefield</option>
                  </select>
                </div>
                <div className="space-y-1">
                  <label className="text-xs font-semibold">Destination (Target)</label>
                  <select className="w-full h-9 rounded-md border border-input bg-background px-3 py-1 text-xs">
                    <option>Sub-WH Indiranagar (VM-04)</option>
                    <option>Sub-WH Whitefield</option>
                    <option>Vending Machine #07 (Tech Park)</option>
                  </select>
                </div>
                <div className="space-y-1">
                  <label className="text-xs font-semibold">Select Product</label>
                  <select className="w-full h-9 rounded-md border border-input bg-background px-3 py-1 text-xs">
                    <option>Red Bull 250ml (Stock: 120 units)</option>
                    <option>Coca Cola 300ml (Stock: 150 units)</option>
                    <option>Doritos Cheese 50g (Stock: 80 units)</option>
                  </select>
                </div>
                <div className="space-y-1">
                  <label className="text-xs font-semibold">Dispatch Quantity</label>
                  <Input type="number" min="1" defaultValue="40" className="text-xs" />
                </div>
              </CardContent>
              <div className="p-4 border-t border-border flex justify-end gap-2 bg-muted/20">
                <Button type="button" variant="outline" size="sm" onClick={() => setIsCreateModalOpen(false)}>
                  Cancel
                </Button>
                <Button type="submit" size="sm">
                  Generate DC & Dispatch
                </Button>
              </div>
            </form>
          </Card>
        </div>
      )}
    </div>
  )
}
