"""
app/domain/enums.py — All System Enumerations

PATTERN: Python StrEnum for all domain-level enumerated values.

WHY centralized enums (not per-module):
    Enums define the vocabulary of the entire domain. Scattering them across
    modules creates import cycles and inconsistency. When adding a new status
    or role, there is exactly ONE place to edit — this file.

WHY StrEnum (not IntEnum, not plain strings):
    - StrEnum: Values are strings (e.g., "admin"). Stored as VARCHAR in DB.
      Human-readable in database queries, logs, API responses.
    - IntEnum: Values are integers (e.g., 1 = admin). Fast storage, but
      opaque in debugging. Adding new values changes ordinal mapping.
    - Plain strings: No type safety, no IDE completion, no exhaustiveness check.

WHY not database-stored "lookup tables" for statuses:
    Statuses (like POStatus, GRNStatus) are CODE-driven, not data-driven.
    Changing a status requires a code deployment. Making it dynamic (in DB)
    adds complexity without value. Reference tables are appropriate for
    user-configurable data (GST slabs, warehouse zones, etc.).

DATABASE:
    All StrEnum values are stored as PostgreSQL VARCHAR with CHECK constraints
    generated by SQLAlchemy's Enum type. This prevents invalid values at
    the DB level — not just at the application level.

SCALABILITY:
    Adding a new status to an existing flow requires:
    1. Adding to the enum (this file)
    2. An Alembic migration to update the CHECK constraint
    3. Service logic to handle the new state
    No other changes — the API serializes enums transparently via Pydantic.
"""

from __future__ import annotations

from enum import StrEnum


# ── User & Authentication ─────────────────────────────────────────────────────
class UserRole(StrEnum):
    """
    RBAC roles — ordered from highest to lowest privilege.

    ADMIN: Full system access. Can manage users, company settings.
    WAREHOUSE_MANAGER: Manages warehouse ops, transfers, GRNs.
    INVENTORY_MANAGER: Manages stock levels, reservations, adjustments.
    PROCUREMENT: Creates and manages Purchase Orders.
    DELIVERY_MANAGER: Manages Delivery Challans and dispatch.
    VIEWER: Read-only access. Reports and dashboard only.
    """

    ADMIN = "admin"
    WAREHOUSE_MANAGER = "warehouse_manager"
    INVENTORY_MANAGER = "inventory_manager"
    PROCUREMENT = "procurement"
    DELIVERY_MANAGER = "delivery_manager"
    VIEWER = "viewer"


class UserStatus(StrEnum):
    ACTIVE = "active"
    INACTIVE = "inactive"
    SUSPENDED = "suspended"


# ── Product & Catalog ─────────────────────────────────────────────────────────
class ProductStatus(StrEnum):
    ACTIVE = "active"
    INACTIVE = "inactive"
    DISCONTINUED = "discontinued"
    OUT_OF_STOCK = "out_of_stock"


class StockCondition(StrEnum):
    """Condition of stock — used in GRN and inventory adjustments."""

    GOOD = "good"           # Sellable inventory
    DAMAGED = "damaged"     # Unsellable, to be written off
    EXPIRED = "expired"     # Past expiry date
    QUARANTINE = "quarantine"  # Held pending quality check


class GSTRate(StrEnum):
    """Indian GST slabs. Values stored as strings for display convenience."""

    ZERO = "0"
    FIVE = "5"
    TWELVE = "12"
    EIGHTEEN = "18"
    TWENTY_EIGHT = "28"


# ── Purchase Order ─────────────────────────────────────────────────────────────
class POStatus(StrEnum):
    """
    Purchase Order lifecycle states.

    State machine:
        DRAFT → PENDING_APPROVAL → APPROVED → PARTIALLY_RECEIVED
             ↘                 ↘             → FULLY_RECEIVED
               CANCELLED         REJECTED
    """

    DRAFT = "draft"
    PENDING_APPROVAL = "pending_approval"
    APPROVED = "approved"
    REJECTED = "rejected"
    PARTIALLY_RECEIVED = "partially_received"
    FULLY_RECEIVED = "fully_received"
    CANCELLED = "cancelled"


class POLineItemStatus(StrEnum):
    PENDING = "pending"
    PARTIALLY_RECEIVED = "partially_received"
    FULLY_RECEIVED = "fully_received"
    CANCELLED = "cancelled"


# ── Goods Receipt Note ────────────────────────────────────────────────────────
class GRNStatus(StrEnum):
    """
    GRN lifecycle states.

    State machine:
        DRAFT → IN_PROGRESS → COMPLETED
                            ↘ DISCREPANCY  (quantities don't match PO)
    """

    DRAFT = "draft"
    IN_PROGRESS = "in_progress"
    COMPLETED = "completed"
    DISCREPANCY = "discrepancy"


# ── Inventory ──────────────────────────────────────────────────────────────────
class InventoryTransactionType(StrEnum):
    """
    All possible inventory movement types.

    WHY enum (not free text): Inventory ledger integrity requires that every
    transaction has a known type. Reporting groups by transaction type.
    An unknown type breaks reports silently.
    """

    # Stock additions
    GRN_RECEIPT = "grn_receipt"         # Stock received via GRN
    TRANSFER_IN = "transfer_in"         # Stock transferred in from another warehouse
    RETURN_FROM_CUSTOMER = "return_from_customer"
    MANUAL_ADJUSTMENT_IN = "manual_adjustment_in"

    # Stock deductions
    SALE = "sale"                       # Stock consumed by a customer order
    TRANSFER_OUT = "transfer_out"       # Stock transferred out to another warehouse
    DAMAGED_WRITE_OFF = "damaged_write_off"
    EXPIRED_WRITE_OFF = "expired_write_off"
    MANUAL_ADJUSTMENT_OUT = "manual_adjustment_out"

    # Reservations (no physical movement, but changes available count)
    RESERVATION = "reservation"         # Stock reserved for pending order
    RESERVATION_RELEASE = "reservation_release"  # Reservation cancelled/expired


class InventoryAdjustmentReason(StrEnum):
    PHYSICAL_COUNT = "physical_count"   # Stock take result
    DAMAGED_IN_WAREHOUSE = "damaged_in_warehouse"
    THEFT = "theft"
    SYSTEM_CORRECTION = "system_correction"
    EXPIRY = "expiry"
    QUALITY_REJECTION = "quality_rejection"
    OTHER = "other"


# ── Warehouse & Transfers ──────────────────────────────────────────────────────
class WarehouseType(StrEnum):
    MAIN_WAREHOUSE = "main_warehouse"
    DARK_STORE = "dark_store"
    DISTRIBUTION_CENTER = "distribution_center"


class WarehouseStatus(StrEnum):
    ACTIVE = "active"
    INACTIVE = "inactive"
    UNDER_RENOVATION = "under_renovation"


class TransferStatus(StrEnum):
    """
    Warehouse transfer lifecycle.

    State machine:
        REQUESTED → APPROVED → IN_TRANSIT → RECEIVED → COMPLETED
                  ↘ REJECTED
    """

    REQUESTED = "requested"
    APPROVED = "approved"
    REJECTED = "rejected"
    IN_TRANSIT = "in_transit"
    RECEIVED = "received"
    COMPLETED = "completed"
    CANCELLED = "cancelled"


# ── Customer Orders ────────────────────────────────────────────────────────────
class OrderStatus(StrEnum):
    """
    Customer order simulation lifecycle.

    State machine:
        CREATED → STOCK_RESERVED → PAYMENT_PENDING → PAYMENT_CONFIRMED
                                 ↘ RESERVATION_EXPIRED → CANCELLED
                                                      ↘ PAYMENT_FAILED → CANCELLED
                 PAYMENT_CONFIRMED → DISPATCHED → DELIVERED
    """

    CREATED = "created"
    STOCK_RESERVED = "stock_reserved"
    PAYMENT_PENDING = "payment_pending"
    PAYMENT_CONFIRMED = "payment_confirmed"
    PAYMENT_FAILED = "payment_failed"
    RESERVATION_EXPIRED = "reservation_expired"
    DISPATCHED = "dispatched"
    DELIVERED = "delivered"
    CANCELLED = "cancelled"
    REFUNDED = "refunded"


class PaymentStatus(StrEnum):
    PENDING = "pending"
    SUCCESS = "success"
    FAILED = "failed"
    REFUNDED = "refunded"


class PaymentMethod(StrEnum):
    UPI = "upi"
    CARD = "card"
    NET_BANKING = "net_banking"
    CASH_ON_DELIVERY = "cash_on_delivery"
    WALLET = "wallet"


# ── Delivery Challan ───────────────────────────────────────────────────────────
class DCStatus(StrEnum):
    """
    Delivery Challan (DC) lifecycle.

    State machine:
        GENERATED → ASSIGNED → DISPATCHED → DELIVERED
                  ↘ ON_HOLD               ↘ RETURNED
    """

    GENERATED = "generated"
    ASSIGNED = "assigned"
    ON_HOLD = "on_hold"
    DISPATCHED = "dispatched"
    DELIVERED = "delivered"
    RETURNED = "returned"
    CANCELLED = "cancelled"


# ── Supplier ───────────────────────────────────────────────────────────────────
class SupplierStatus(StrEnum):
    ACTIVE = "active"
    INACTIVE = "inactive"
    BLACKLISTED = "blacklisted"


class SupplierRating(StrEnum):
    """Supplier performance tier — set by procurement based on history."""

    EXCELLENT = "excellent"     # > 95% on-time, < 1% defect rate
    GOOD = "good"              # > 85% on-time, < 3% defect rate
    AVERAGE = "average"        # > 70% on-time, < 5% defect rate
    POOR = "poor"              # Below threshold — under review
    BLACKLISTED = "blacklisted"  # No new POs allowed


# ── Document Types ─────────────────────────────────────────────────────────────
class DocumentType(StrEnum):
    """Enumeration of all documents that can be generated as PDF."""

    PURCHASE_ORDER = "purchase_order"
    GRN = "grn"
    DELIVERY_CHALLAN = "delivery_challan"
    INVENTORY_REPORT = "inventory_report"
    STOCK_LEDGER = "stock_ledger"


# ── Sort Direction ─────────────────────────────────────────────────────────────
class SortDirection(StrEnum):
    ASC = "asc"
    DESC = "desc"
